### ISSUE TITLE
Update to work with November 2024 website?

### ISSUE THREAD

**Issue by Aralox** [longzheng/southeastwater-usage-scraper#1]
Hi mate, thanks for your work. Looks like the south east water site has changed significantly. Are you able to update your code to work with the new site?
Thank you!

**Comment by longzheng** [comment]
Ah it looks like they've changed the website considerably, will have to investigate.

**Comment by longzheng** [comment]
@Aralox I've updated it to handle the new layout, give it a try.

**Comment by Aralox** [comment]
Thanks heaps for your work @longzheng. You're quick!
I plan to set up a task to run this every day to update data in an influx DB I've hosted locally alongside home assistant. On a bit of a mission to get live data from the Landis+Gyr W350 water sensors we have. This is the closest solution so far. Thanks again.

**Comment by longzheng** [comment]
Cool. I did briefly look into the water meter as well, but I assume the data is encrypted by default (similar to electricity meters).

Let me know if you find anything interesting.

**Comment by longzheng** [comment]
@Aralox I just noticed I accidentally commited the non-headless mode when I was testing. I just pushed another commit that makes it headless again.

**Comment by Aralox** [comment]
No worries, I'm finding the non headless amusing as I get it to process the last couple years of backlog data. The sew site is dodgy and times out every 50 days or so for me, but I just change the loop initial variable and rerun it.

**Comment by longzheng** [comment]
Oh interesting, what are you seeing with the timeout, the page is an error or something else? 

I'm keen to see how I can try handle/fix that.

**Comment by Aralox** [comment]
Oh apologies, it's influx db, it's my end. It sorted itself out after a bit and went through the rest without problems. The error was: 
Processing 2024-03-16 - 246 of 600
WARN: Write to InfluxDB failed (attempt: 1). t [RequestTimedOutError]: Request timed out
    at ClientRequest.<anonymous> (D:\Projects\southeastwater-usage-scraper\node_modules\@influxdata\influxdb-client\src\impl\node\NodeHttpTransport.ts:432:23)
    at ClientRequest.emit (node:events:519:28)
    at Socket.emitRequestTimeout (node:_http_client:845:9)
    at Object.onceWrapper (node:events:633:28)
    at Socket.emit (node:events:531:35)
    at Socket._onTimeout (node:net:591:8)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

t [RequestTimedOutError]: Request timed out
    at ClientRequest.<anonymous> (D:\Projects\southeastwater-usage-scraper\node_modules\@influxdata\influxdb-client\src\impl\node\NodeHttpTransport.ts:432:23)
    at ClientRequest.emit (node:events:519:28)
    at Socket.emitRequestTimeout (node:_http_client:845:9)
    at Object.onceWrapper (node:events:633:28)
    at Socket.emit (node:events:531:35)
    at Socket._onTimeout (node:net:591:8)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)

Node.js v20.16.0

I guess a potential improvement is to give it a few retries or something like that. Either way, this code is already gold.

PS: The script doesn't actually end for me, it hangs on e.g. "Processing 2022-09-09 - 800 of 800". I don't mind and haven't bothered looking into it, but thought I'd raise it. If it becomes an issue for my automation I'll have a look.

**Comment by longzheng** [comment]
Ah, I think the influx library automatically retries but I'm causing it to flush on every new entry which is not ideal.

I made some tweaks. Can you try the branch `influx-tweak` when you get a chance https://github.com/longzheng/southeastwater-usage-scraper/tree/influx-tweak

**Comment by Aralox** [comment]
Just ran it on 800 days, it completed without any problems. Nice work!

**Comment by longzheng** [comment]
Awesome.

By the way, can I ask how you found this project?

**Comment by Aralox** [comment]
I googled "southeastwater usage scraper" (without much hope, so I was delighted to find your twitter post)
![image](https://github.com/user-attachments/assets/8b6e76e5-e471-4e4d-952c-a4a869d06bca)

**Comment by longzheng** [comment]
Awesome 🎉
